import { useState } from "react";
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell,
} from "recharts";
import jsPDF from "jspdf";

export default function Dashboard() {
  const metrics = [
    { name: "Empathy", value: 82 },
    { name: "Cohesion", value: 76 },
    { name: "Engagement", value: 88 },
    { name: "Bias Risk", value: 30 },
  ];

  const COLORS = ["#4F46E5", "#06B6D4", "#10B981", "#F59E0B"];
  const [reflection, setReflection] = useState("");

  // 🧾 PDF Download Handler
  const downloadReport = () => {
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Culture Readiness Report", 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text("A summary of key empathy, cohesion, and inclusion metrics.", 20, 30);

    // Metrics section
    doc.setFont("helvetica", "bold");
    doc.text("Metrics Overview:", 20, 45);
    doc.setFont("helvetica", "normal");
    let y = 55;
    metrics.forEach((m) => {
      doc.text(`${m.name}: ${m.value}%`, 25, y);
      y += 10;
    });

    // Reflection
    doc.setFont("helvetica", "bold");
    doc.text("Reflection:", 20, y + 5);
    doc.setFont("helvetica", "normal");
    doc.text(reflection || "No reflection entered.", 25, y + 15, { maxWidth: 160 });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Trading Places™ Prototype | LSBU 2025", 20, 280);

    doc.save("Culture_Readiness_Report.pdf");
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">Culture Pulse Dashboard</h1>
          <p className="text-gray-600 mt-2">
            A visual representation of empathy, inclusion, and engagement across the organisation.
          </p>
        </div>

        {/* 📄 Download Button */}
        <button
          onClick={downloadReport}
          className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-lg shadow-md transition"
        >
          Download Report
        </button>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-10">
        {metrics.map((m, index) => (
          <div key={index} className="bg-white rounded-xl shadow-md p-6 text-center">
            <h3 className="text-lg font-semibold text-gray-700">{m.name}</h3>
            <p className="text-3xl font-bold text-indigo-600 mt-2">{m.value}%</p>
          </div>
        ))}
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-10">
        <div className="bg-white rounded-xl shadow-md p-6">
          <h3 className="text-lg font-semibold text-gray-700 mb-4">Culture Metrics Overview</h3>
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={metrics}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="value">
                {metrics.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="bg-white rounded-xl shadow-md p-6">
          <h3 className="text-lg font-semibold text-gray-700 mb-4">Engagement Distribution</h3>
          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie
                data={metrics}
                dataKey="value"
                outerRadius={100}
                label
              >
                {metrics.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Reflection Box */}
      <div className="bg-white rounded-xl shadow-md p-6">
        <h3 className="text-lg font-semibold text-gray-700 mb-2">Reflection</h3>
        <p className="text-gray-600 mb-3">
          How can your team improve cultural intelligence and inclusion next quarter?
        </p>
        <textarea
          className="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500"
          rows="3"
          placeholder="Write your reflection here..."
          value={reflection}
          onChange={(e) => setReflection(e.target.value)}
        ></textarea>
      </div>
    </div>
  );
}
